site_name: Joergs mkDocs
dev_addr: '0.0.0.0:8080'
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png
site_author: "Jörg Hofmann"
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Einrichtung: user-guide/getting-started.md
  - Impressum: legal/imprint.md
